version: '3.8'
services:
  mariadb:
    image: mariadb
    restart: always
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./data/star_scheme.sql:/docker-entrypoint-initdb.d/1.sql

  python-script:
    build:
      context: .
      dockerfile: Dockerfile.python
    # restart: always
    container_name: python
    depends_on:
      - mariadb
    volumes:
      - ./:/app
    working_dir: /app
    command: python3 script.py
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
